apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uuss
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/abhindas-tenant/app-sample-go-basic/devfile-sample-uuss@sha256:1899b8fbb926b7646b69010b1f26c716d0f628394eab515729027bcb074a8297
        name: my-nodejs
        resources: {}
status: {}
